#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""API provider discovery, model selection, and OpenAI-compatible chat calls."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any
from urllib.error import HTTPError
from urllib.request import Request, urlopen


ROOT = Path(__file__).resolve().parents[1]
ENV_PATH = ROOT / ".env"
DEFAULT_TIMEOUT_SECONDS = 20

PROVIDERS: dict[str, dict[str, Any]] = {
    "xiaomi-mimo": {
        "name": "小米 MiMo",
        "base_url": "https://api.xiaomimimo.com/v1",
        "fallback_models": ["mimo-v2.5-pro"],
        "docs": "https://platform.xiaomimimo.com/docs",
    },
    "deepseek": {
        "name": "DeepSeek",
        "base_url": "https://api.deepseek.com",
        "fallback_models": ["deepseek-v4-pro", "deepseek-v4-flash"],
        "docs": "https://api-docs.deepseek.com/",
    },
    "openai": {
        "name": "OpenAI",
        "base_url": "https://api.openai.com/v1",
        "fallback_models": ["gpt-5.2", "gpt-5-mini"],
        "docs": "https://platform.openai.com/docs/models",
    },
    "openai-compatible": {
        "name": "自定义 OpenAI 兼容接口",
        "base_url": "",
        "fallback_models": [],
        "docs": "",
    },
}


def read_env(path: Path = ENV_PATH) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def write_env(values: dict[str, str], path: Path = ENV_PATH) -> None:
    lines = [
        "# Local Knowledge Base Agent configuration",
        "# Generated by scripts/configure_api.py or scripts/setup_agent.py",
        "",
    ]
    for key, value in values.items():
        safe_value = str(value).replace("\\", "\\\\").replace("\n", "")
        lines.append(f"{key}={safe_value}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def infer_provider(base_url: str = "", api_key: str = "", hint: str = "") -> str:
    hint = hint.strip().lower()
    base_url = base_url.strip().lower()
    api_key = api_key.strip().lower()
    if hint in PROVIDERS:
        return hint
    if "xiaomimimo.com" in base_url or api_key.startswith("sk-mimo"):
        return "xiaomi-mimo"
    if "deepseek.com" in base_url or api_key.startswith("sk-ds"):
        return "deepseek"
    if "openai.com" in base_url:
        return "openai"
    return "openai-compatible"


def token_plan_rejected(base_url: str, api_key: str) -> bool:
    return "token-plan" in base_url.lower() or api_key.lower().startswith("tp-")


def default_base_url(provider: str) -> str:
    return str(PROVIDERS.get(provider, PROVIDERS["openai-compatible"]).get("base_url", ""))


def fallback_models(provider: str) -> list[str]:
    return list(PROVIDERS.get(provider, PROVIDERS["openai-compatible"]).get("fallback_models", []))


def request_headers(provider: str, api_key: str) -> dict[str, str]:
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        "User-Agent": "local-knowledge-agent/1.0",
    }
    if provider == "xiaomi-mimo":
        headers["api-key"] = api_key
    return headers


def api_request(
    method: str,
    url: str,
    provider: str,
    api_key: str,
    payload: dict[str, Any] | None = None,
    timeout: int = DEFAULT_TIMEOUT_SECONDS,
) -> dict[str, Any]:
    body = json.dumps(payload, ensure_ascii=False).encode("utf-8") if payload is not None else None
    request = Request(url, data=body, headers=request_headers(provider, api_key), method=method)
    try:
        with urlopen(request, timeout=timeout) as response:
            return json.loads(response.read().decode("utf-8", errors="replace"))
    except HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace").strip()
        raise RuntimeError(f"HTTP {exc.code}: {detail[:500]}") from exc


def chat_capable_model(provider: str, model: str) -> bool:
    lowered = model.lower()
    if provider == "xiaomi-mimo":
        return lowered.startswith("mimo")
    if provider == "deepseek":
        return lowered.startswith("deepseek")
    excluded = (
        "embedding",
        "moderation",
        "audio",
        "realtime",
        "transcribe",
        "tts",
        "whisper",
        "dall-e",
        "image",
        "sora",
        "babbage",
        "davinci",
        "computer-use",
    )
    return not any(item in lowered for item in excluded)


def discover_models(provider: str, base_url: str, api_key: str, timeout: int = 12) -> dict[str, Any]:
    provider = infer_provider(base_url, api_key, provider)
    base_url = (base_url or default_base_url(provider)).rstrip("/")
    if token_plan_rejected(base_url, api_key):
        return {
            "ok": False,
            "provider": provider,
            "base_url": base_url,
            "models": [],
            "error": "MiMo Token Plan 的 tp- key 仅限编程工具使用，不能作为本应用后端。",
        }
    try:
        data = api_request("GET", f"{base_url}/models", provider, api_key, timeout=timeout)
        models = [
            str(item.get("id", "")).strip()
            for item in data.get("data", [])
            if isinstance(item, dict) and str(item.get("id", "")).strip()
        ]
        models = sorted({model for model in models if chat_capable_model(provider, model)})
        if models:
            return {"ok": True, "provider": provider, "base_url": base_url, "models": models, "discovered": True}
    except Exception as exc:  # noqa: BLE001
        error = str(exc)
    else:
        error = "接口没有返回可用的文本模型。"

    models = fallback_models(provider)
    return {
        "ok": bool(models),
        "provider": provider,
        "base_url": base_url,
        "models": models,
        "discovered": False,
        "warning": f"在线模型发现失败，已使用提供商默认模型列表：{error}" if models else error,
    }


def chat_completion(
    provider: str,
    base_url: str,
    api_key: str,
    model: str,
    messages: list[dict[str, str]],
    temperature: float = 0.1,
    timeout: int = DEFAULT_TIMEOUT_SECONDS,
) -> str:
    provider = infer_provider(base_url, api_key, provider)
    base_url = (base_url or default_base_url(provider)).rstrip("/")
    if token_plan_rejected(base_url, api_key):
        raise RuntimeError("MiMo Token Plan 的 tp- key 仅限编程工具使用，不能作为本应用后端。")
    data = api_request(
        "POST",
        f"{base_url}/chat/completions",
        provider,
        api_key,
        payload={"model": model, "temperature": temperature, "messages": messages},
        timeout=timeout,
    )
    answer = data["choices"][0]["message"]["content"]
    if isinstance(answer, list):
        answer = "".join(str(item.get("text", "")) for item in answer if isinstance(item, dict))
    return str(answer).strip()


def validate_chat_model(provider: str, base_url: str, api_key: str, model: str, timeout: int = 20) -> dict[str, Any]:
    try:
        answer = chat_completion(
            provider,
            base_url,
            api_key,
            model,
            [
                {"role": "system", "content": "只回答：连接成功"},
                {"role": "user", "content": "请验证连接。"},
            ],
            temperature=0.0,
            timeout=timeout,
        )
        return {"ok": True, "answer": answer}
    except Exception as exc:  # noqa: BLE001
        return {"ok": False, "error": str(exc)}


def provider_options() -> list[dict[str, str]]:
    return [
        {"id": provider_id, "name": str(config["name"]), "base_url": str(config["base_url"])}
        for provider_id, config in PROVIDERS.items()
    ]
