#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Interactive setup for Local Knowledge Base Agent."""

from __future__ import annotations

import json
import sqlite3
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ENV_PATH = ROOT / ".env"
RAW_DIR = ROOT / "knowledge_base" / "raw"
INDEX_DIR = ROOT / "knowledge_base" / "index"
PROCESSED_DIR = ROOT / "knowledge_base" / "processed"


def ask_yes_no(prompt: str, default: bool = False) -> bool:
    suffix = "Y/n" if default else "y/N"
    raw = input(f"{prompt} [{suffix}]: ").strip().lower()
    if not raw:
        return default
    return raw in {"y", "yes", "1", "true"}


def ask_value(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    raw = input(f"{prompt}{suffix}: ").strip()
    return raw or default


def sqlite_has_fts5() -> bool:
    try:
        conn = sqlite3.connect(":memory:")
        conn.execute("CREATE VIRTUAL TABLE test_fts USING fts5(text)")
        conn.close()
        return True
    except sqlite3.Error:
        return False


def write_env(values: dict[str, str]) -> None:
    lines = [
        "# Local Knowledge Base Agent configuration",
        "# Generated by scripts/setup_agent.py",
        "",
    ]
    for key, value in values.items():
        safe_value = value.replace("\\", "\\\\").replace("\n", "")
        lines.append(f"{key}={safe_value}")
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def run_update() -> int:
    command = [sys.executable, str(ROOT / "scripts" / "manage_knowledge_base.py"), "update", str(RAW_DIR)]
    proc = subprocess.run(command, cwd=str(ROOT), text=True, capture_output=True)
    if proc.stdout:
        print(proc.stdout.strip())
    if proc.stderr:
        print(proc.stderr.strip(), file=sys.stderr)
    return proc.returncode


def main() -> int:
    print("Local Knowledge Base Agent setup")
    print(f"Project: {ROOT}")
    print(f"Python: {sys.executable}")

    RAW_DIR.mkdir(parents=True, exist_ok=True)
    INDEX_DIR.mkdir(parents=True, exist_ok=True)
    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

    if not sqlite_has_fts5():
        print("ERROR: 当前 Python 的 sqlite3 不支持 FTS5，无法启用本地全文索引。", file=sys.stderr)
        return 2

    use_api = ask_yes_no("是否配置大模型 API 用于答案润色/总结？没有也可以纯本地命令行问答", default=False)
    values = {
        "LKA_USE_API": "false",
        "LKA_API_PROVIDER": "none",
        "LKA_API_BASE_URL": "",
        "LKA_API_KEY": "",
        "LKA_API_MODEL": "",
        "LKA_API_TIMEOUT_SECONDS": "20",
    }
    if use_api:
        provider = ask_value("API provider 名称", "openai-compatible")
        base_url = ask_value("API base URL", "https://api.openai.com/v1")
        model = ask_value("模型名称", "gpt-4o-mini")
        api_key = ask_value("API key")
        if api_key:
            values.update(
                {
                    "LKA_USE_API": "true",
                    "LKA_API_PROVIDER": provider,
                    "LKA_API_BASE_URL": base_url.rstrip("/"),
                    "LKA_API_KEY": api_key,
                    "LKA_API_MODEL": model,
                }
            )
        else:
            print("未输入 API key，将保持纯本地命令行回答模式。")

    write_env(values)
    print(f"配置已写入: {ENV_PATH}")

    raw_files = [path for path in RAW_DIR.rglob("*") if path.is_file()]
    if raw_files and ask_yes_no("是否现在增量更新知识库索引？", default=True):
        code = run_update()
        if code != 0:
            return code
    elif not raw_files:
        print("raw 目录暂无资料。后续放入资料后运行: .\\run-agent.bat update")

    summary = {
        "setup_complete": True,
        "api_enabled": values["LKA_USE_API"] == "true",
        "raw_dir": str(RAW_DIR),
        "env_file": str(ENV_PATH),
    }
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
